import { Movie } from '@/types';

export const mockMovies: Movie[] = [
  {
    id: '1',
    title: 'IT',
    genre: ['Terror', 'Thriller'],
    year: 2017,
    director: 'Andy Muschietti',
    actors: ['Bill Skarsgård', 'Jaeden Martell', 'Finn Wolfhard'],
    synopsis: 'Un grupo de niños se enfrenta al malvado payaso Pennywise.',
    poster: 'https://image.tmdb.org/t/p/w500/9E2y5Q7WlCVNEhP5GiVTjhEhx1o.jpg',
    trailer: 'https://www.youtube.com/watch?v=xKJmEC5ieOk',
    rating: 7.3,
    duration: 135,
    keywords: ['payaso', 'terror', 'niños', 'stephen king', 'miedo', 'it', 'pennywise'],
    releaseDate: new Date('2017-09-08')
  },
  {
    id: '2',
    title: 'Payaso Diabólico',
    genre: ['Terror', 'Slasher'],
    year: 2016,
    director: 'Damien Leone',
    actors: ['Jenna Kanell', 'Samantha Scaffidi', 'David Howard Thornton'],
    synopsis: 'Un payaso siniestro aterroriza a una ciudad en Halloween.',
    poster: 'https://image.tmdb.org/t/p/w500/ggZGnJLzO3BTu7ysuuIzou3Oex5.jpg',
    trailer: 'https://www.youtube.com/watch?v=Prv-9WqhYGo',
    rating: 5.6,
    duration: 84,
    keywords: ['payaso', 'terror', 'halloween', 'asesino', 'art the clown', 'miedo'],
    releaseDate: new Date('2016-10-15')
  },
  {
    id: '3',
    title: 'Joker',
    genre: ['Drama', 'Crimen', 'Thriller'],
    year: 2019,
    director: 'Todd Phillips',
    actors: ['Joaquin Phoenix', 'Robert De Niro', 'Zazie Beetz'],
    synopsis: 'La historia del origen del icónico villano Joker.',
    poster: 'https://image.tmdb.org/t/p/w500/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg',
    trailer: 'https://www.youtube.com/watch?v=zAGVQLHvwOY',
    rating: 8.4,
    duration: 122,
    keywords: ['payaso', 'batman', 'villano', 'gotham', 'joaquin phoenix', 'drama', 'origen'],
    releaseDate: new Date('2019-10-04')
  },
  {
    id: '4',
    title: 'Batman: The Dark Knight',
    genre: ['Acción', 'Crimen', 'Drama'],
    year: 2008,
    director: 'Christopher Nolan',
    actors: ['Christian Bale', 'Heath Ledger', 'Aaron Eckhart'],
    synopsis: 'Batman se enfrenta al Joker en una batalla épica por Gotham.',
    poster: 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
    trailer: 'https://www.youtube.com/watch?v=EXeTwQWrcwY',
    rating: 9.0,
    duration: 152,
    keywords: ['batman', 'joker', 'payaso', 'gotham', 'heath ledger', 'superhéroe', 'acción'],
    releaseDate: new Date('2008-07-18')
  },
  {
    id: '5',
    title: 'Avengers: Endgame',
    genre: ['Acción', 'Aventura', 'Ciencia Ficción'],
    year: 2019,
    director: 'Anthony Russo, Joe Russo',
    actors: ['Robert Downey Jr.', 'Chris Evans', 'Mark Ruffalo'],
    synopsis: 'Los Vengadores se unen para una batalla final contra Thanos.',
    poster: 'https://image.tmdb.org/t/p/w500/or06FN3Dka5tukK1e9sl16pB3iy.jpg',
    trailer: 'https://www.youtube.com/watch?v=TcMBFSGVi1c',
    rating: 8.4,
    duration: 181,
    keywords: ['superhéroes', 'marvel', 'avengers', 'thanos', 'iron man', 'acción'],
    releaseDate: new Date('2019-04-26')
  },
  {
    id: '6',
    title: 'Interstellar',
    genre: ['Ciencia Ficción', 'Drama'],
    year: 2014,
    director: 'Christopher Nolan',
    actors: ['Matthew McConaughey', 'Anne Hathaway', 'Jessica Chastain'],
    synopsis: 'Un grupo de astronautas viaja a través de un agujero de gusano.',
    poster: 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
    trailer: 'https://www.youtube.com/watch?v=zSWdZVtXT7E',
    rating: 8.6,
    duration: 169,
    keywords: ['espacio', 'tiempo', 'ciencia ficción', 'nolan', 'astronautas', 'futuro'],
    releaseDate: new Date('2014-11-07')
  }
];